const cityNameList = [
    'Queretaro, Queretaro, Mexico',
    'Mexico City, Mexico',
    'Guadalajara, Jalisco, Mexico',
    'Monterrey, Nuevo Leon, Mexico',
    'Puebla, Puebla, Mexico',
    'Tijuana, Baja California, Mexico',
    'Ciudad Juarez, Chihuahua, Mexico',
    'Chihuahua, Chihuahua, Mexico',
    'Cancun, Quintana Roo, Mexico',
    'Hermosillo, Sonora, Mexico',
    'Toluca, Mexico',
    'Managua, Nicaragua',
    'San Salvador, El Salvador',
    'San Jose, Costa Rica',
    'Panama City, Panama',
    'Bogota, Colombia',
    'Tuxtla Gutierrez, Chiapas, Mexico',
    'London, England',
    'Paris, France',
    'Madrid, Spain',
    'Berlin, Germany',
    'Rome, Italy',
    'Barcelona, Spain',
    'Los Angeles, California, USA',
    'Hermitage, Pennsylvania, USA',
    'New York, New York, USA',
    'Chicago, Illinois, USA',
    'Houston, Texas, USA',
    'Phoenix, Arizona, USA',
    'Philadelphia, Pennsylvania, USA',
    'San Antonio, Texas, USA',
    'Lucedale, Mississippi, USA',
    'Mobile, Alabama, USA',
    'Miami, Florida, USA',
    'Luxembourg, Luxembourg',
    'Las Vegas, Nevada, USA',
    'Guffey, Colorado',
    'Columbine, Colorado',
    'San Diego, California',
    'Dallas, Texas',
    'Capetown, South Africa',
    'Sydney, Australia',
    'Melbourne, Australia',
    'Tokyo, Japan',
    'Osaka, Japan',
    'Kyoto, Japan',
    'Moscow, Russia',
    'Saint Petersburg, Russia',
    'Orlando, Florida',
    'Kiev, Ukraine',
    'Minsk, Belarus',
    'Beijing, China',
    'Shanghai, China',
    'Hong Kong, China',
    'Bangkok, Thailand',
    'Singapore, Singapore',
    'Seoul, South Korea',
    'New Delhi, India',
    'Mumbai, India',
    'Kolkata, India',
    'Jakarta, Indonesia',
    'Manila, Philippines',
    'Caracas, Venezuela',
    'Santiago, Chile',
    'Lisbon, Portugal',
    'Amsterdam, Netherlands',
    'Athens, Greece',
    'Copenhagen, Denmark',
    'Quito, Ecuador',
    'Havana, Cuba',
    'Quebec City, Quebec',
    'Toronto, Ontario',
    'Montreal, Quebec',
    'Vancouver, British Columbia',
    'Fiji, Fiji Islands',
    'Calgary, Alberta',
    'Edmonton, Alberta',
    'Ottawa, Ontario',
    'Winnipeg, Manitoba',
    'Halifax, Nova Scotia',
    'Buenos Aires, Argentina',
    'Sao Paulo, Brazil',
    'Rio de Janeiro, Brazil',
    'Lima, Peru',
    'Johannesburg, South Africa',
    'Jhonson city, Tennessee',
    'Queens, New York',
    'Jerusalem, Israel',
    'Dubai, United Arab Emirates',
    'Riyadh, Saudi Arabia',
    'Abu Dhabi, United Arab Emirates',
    'Baku, Azerbaijan',
    'Tehran, Iran',
    'Baghdad, Iraq',
    'Kabul, Afghanistan',
    'Kathmandu, Nepal',
    'Dhaka, Bangladesh',
    'Kuala Lumpur, Malaysia',
    'Singapore, Singapore',
    'Hanoi, Vietnam',
    'Manila, Philippines',
    'Seoul, South Korea',
    'Pyongyang, North Korea',
  ]

  export default cityNameList;