const cityNameList = [
    'Queretaro, Queretaro',
    'Mexico City, Mexico',
    'Guadalajara, Jalisco',
    'Monterrey, Nuevo Leon',
    'Puebla, Puebla',
    'Tijuana, Baja California',
    'Ciudad Juárez, Chihuahua',
    'London, England',
    'Paris, France',
    'Madrid, Spain',
    'Berlin, Germany',
    'Rome, Italy',
    'Barcelona, Spain',
    'Los Angeles, California',
    'Hermitage, Pennsylvania',
    'New York, New York',
    'Chicago, Illinois',
    'Houston, Texas',
    'Phoenix, Arizona',
    'Philadelphia, Pennsylvania',
    'San Antonio, Texas',
    'Lucedale, Mississippi',
    'Mobile, Alabama',
    'Miami, Florida',
    'Luxembourg, Luxembourg',
    'Las Vegas, Nevada',
    'Guffey, Colorado',
    'Columbine, Colorado',
    'San Diego, California',
    'Dallas, Texas',
    'Capetown, South Africa',
    'Sydney, Australia',
    'Melbourne, Australia',
    'Tokyo, Japan',
    'Osaka, Japan',
    'Kyoto, Japan',
    'Moscow, Russia',
    'Saint Petersburg, Russia',
    'Orlando, Florida',
    'Kiev, Ukraine',
    'Minsk, Belarus',
    'Beijing, China',
    'Shanghai, China',
    'Hong Kong, China',
    'Bangkok, Thailand',
    'Singapore, Singapore',
    'Seoul, South Korea',
    'New Delhi, India',
    'Mumbai, India',
    'Kolkata, India',
    'Jakarta, Indonesia',
    'Manila, Philippines',
    'Caracas, Venezuela',
    'Santiago, Chile',
    'Lisbon, Portugal',
    'Amsterdam, Netherlands',
    'Athens, Greece',
    'Copenhagen, Denmark',
    'Quito, Ecuador',
    'Havana, Cuba',
    'Quebec City, Quebec',
    'Toronto, Ontario',
    'Montreal, Quebec',
    'Vancouver, British Columbia',
    'Calgary, Alberta',
    'Edmonton, Alberta',
    'Ottawa, Ontario',
    'Winnipeg, Manitoba',
    'Halifax, Nova Scotia',
    'Buenos Aires, Argentina',
    'Sao Paulo, Brazil',
    'Rio de Janeiro, Brazil',
    'Bogotá, Colombia',
    'Lima, Peru',
    'Johannesburg, South Africa',
    'Jhonson city, Tennessee',
    'Queens, New York',
    'Jerusalem, Israel',
    'Dubai, United Arab Emirates',
    'Riyadh, Saudi Arabia',
    'Abu Dhabi, United Arab Emirates',
    'Baku, Azerbaijan',
    'Tehran, Iran',
    'Baghdad, Iraq',
    'Kabul, Afghanistan',
    'Kathmandu, Nepal',
    'Dhaka, Bangladesh',
    'Kuala Lumpur, Malaysia',
    'Singapore, Singapore',
    'Hanoi, Vietnam',
    'Manila, Philippines',
    'Seoul, South Korea',
    'Pyongyang, North Korea',
  ]

  export default cityNameList;